### ISSUE TITLE
Deprecation warning when used with ActiveSupport 5+

### ISSUE THREAD

**Issue by lokki007** [makandra/spreewald#73] opened 2017-01-06 17:47 UTC
Every time my Bundler requires spreewald gem I see these 2 warning messages

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from require at /Users/username/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from require at /Users/username/.gem/ruby/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86)
```

Happens on:
require 'cucumber_priority/ambiguous_error_ext'
require 'cucumber_priority/rb_step_definition_ext'

**Comment by henning-koch** [comment] 2017-01-09 07:48
This warning is caused by ActiveSupport 5+, not Bundler.

**Comment by henning-koch** [comment] 2017-01-09 07:50
This has been fixed in Spreewald's dependeny `cucumber_priority`. Run `bundle update cucumber_priority`.

**Closed by henning-koch** 2017-01-09 07:50 UTC
