### ISSUE TITLE
I should not see /REGEXP/ is considerably slower than the non-RegExp variant

### ISSUE THREAD

**Issue by Ichaelus** [makandra/spreewald#94] opened 2019-05-20 22:09 UTC
It surely does not come as a surprise, but matching DOM elements based on a regular expression is *way* slower than by compared to simple text matching. Nevertheless, I observed that especially the "not" combination can make a testsuite painfully slow and would propose looking into it.

## Reason why
* [In Capybara 3, Node#text no longer fully normalizes whitespace, instead returning text as close as possible to "as rendered".](https://github.com/teamcapybara/capybara/blob/master/UPGRADING.md#node)
> This means non-blanking spaces will no longer be collapsed, carriage returns may be returned in text strings, etc. This affects not only the Node#text method but also methods that take a :text option as well as the text related predicates, assertions, and matchers (has_text?, has_content?, assert_text, have_text, etc.).
* This seems to be a little impractical to us, since it differs the way the HTML and Browser correlate: While text might be be split across multiple lines in the HTML, the user might see it in a single line in the browser.
* Ultimately, it led to an increased usage of steps like `I should see /my text\s+split across multiple lines/` for me. 

Well, and since the step `I should not see //` "patiently" traverses the entire DOM with `.//descendant-or-self::*`, executing it takes some precious time on large HTML pages.

**Comment by makmic** [comment] 2019-05-23 07:41
The root cause of my problen has been sepearately inspected and solved in https://github.com/makandra/spreewald/issues/95. As I do no longer see an immediate need to look into this, I'll close this issue for now.

**Closed by makmic** 2019-05-23 07:41 UTC
